export const mainControlRoutes = {
  health: "/health",
  domains: "/domains",
  domainHealth: "/domains/[domain]/health",
  auth: "/auth",
  jobs: "/jobs",
  companies: "/companies",
  applications: "/applications",
  appointments: "/appointments",
  resumes: "/resumes",
  files: "/files",
  backoffice: "/backoffice"
} as const;

export const explicitNextRoutes = {
  landingpage: [
    "/api/auth/login",
    "/api/auth/logout",
    "/api/auth/register/job-seeker",
    "/api/auth/register/company",
    "/api/jobs",
    "/api/jobs/search",
    "/api/jobs/[jobId]",
    "/api/jobs/[jobId]/apply",
    "/api/companies",
    "/api/companies/[companyId]",
    "/api/company/profile/logo",
    "/api/company/jobs/[jobId]/applications",
    "/api/seeker/profile/avatar",
    "/api/seeker/resume/export",
    "/api/seeker/resume/download"
  ],
  backoffice: [
    "/api/auth/login",
    "/api/auth/logout",
    "/api/auth/refresh",
    "/api/admin/me",
    "/api/admin/me/avatar",
    "/api/admin/me/password",
    "/api/admin/dashboard",
    "/api/admin/users",
    "/api/admin/users/[userId]",
    "/api/admin/admin-users",
    "/api/admin/admin-users/[adminUserId]",
    "/api/admin/admin-users/[adminUserId]/suspend",
    "/api/admin/admin-users/[adminUserId]/activate",
    "/api/admin/admin-users/[adminUserId]/reset-password",
    "/api/admin/admin-users/[adminUserId]/role",
    "/api/admin/companies",
    "/api/admin/companies/[companyId]",
    "/api/admin/jobs",
    "/api/admin/jobs/[jobId]",
    "/api/admin/applications",
    "/api/admin/applications/[applicationId]",
    "/api/admin/appointments",
    "/api/admin/appointments/[appointmentId]",
    "/api/admin/packages",
    "/api/admin/packages/[packageId]",
    "/api/admin/roles",
    "/api/admin/roles/[roleId]",
    "/api/admin/roles/[roleId]/permissions",
    "/api/admin/permissions",
    "/api/admin/files",
    "/api/admin/files/[fileId]",
    "/api/admin/settings",
    "/api/admin/settings/[settingKey]",
    "/api/admin/audit-logs"
  ]
} as const;

export const mainControlBackofficeAdminRoutes = {
  dashboard: "/backoffice/admin/dashboard",
  currentAdmin: "/backoffice/admin/me",
  currentAdminAvatar: "/backoffice/admin/me/avatar",
  currentAdminPassword: "/backoffice/admin/me/password",
  users: "/backoffice/admin/users",
  userDetail: "/backoffice/admin/users/[userId]",
  adminUsers: "/backoffice/admin/admin-users",
  adminUserDetail: "/backoffice/admin/admin-users/[adminUserId]",
  adminUserSuspend: "/backoffice/admin/admin-users/[adminUserId]/suspend",
  adminUserActivate: "/backoffice/admin/admin-users/[adminUserId]/activate",
  adminUserResetPassword: "/backoffice/admin/admin-users/[adminUserId]/reset-password",
  adminUserRole: "/backoffice/admin/admin-users/[adminUserId]/role",
  companies: "/backoffice/admin/companies",
  companyDetail: "/backoffice/admin/companies/[companyId]",
  jobs: "/backoffice/admin/jobs",
  jobDetail: "/backoffice/admin/jobs/[jobId]",
  applications: "/backoffice/admin/applications",
  applicationDetail: "/backoffice/admin/applications/[applicationId]",
  appointments: "/backoffice/admin/appointments",
  appointmentDetail: "/backoffice/admin/appointments/[appointmentId]",
  packages: "/backoffice/admin/packages",
  packageDetail: "/backoffice/admin/packages/[packageId]",
  roles: "/backoffice/admin/roles",
  roleDetail: "/backoffice/admin/roles/[roleId]",
  rolePermissions: "/backoffice/admin/roles/[roleId]/permissions",
  permissions: "/backoffice/admin/permissions",
  files: "/backoffice/admin/files",
  fileDetail: "/backoffice/admin/files/[fileId]",
  settings: "/backoffice/admin/settings",
  settingDetail: "/backoffice/admin/settings/[settingKey]",
  auditLogs: "/backoffice/admin/audit-logs"
} as const;

export const mainControlPublicRoutes = {
  authLogin: "/auth/login",
  authLogout: "/auth/logout",
  registerJobSeeker: "/auth/register/job-seeker",
  registerCompany: "/auth/register/company",
  jobs: "/jobs",
  jobSearch: "/jobs/search",
  jobDetail: "/jobs/[jobId]",
  jobApply: "/jobs/[jobId]/apply",
  companies: "/companies",
  companyDetail: "/companies/[companyId]",
  companyProfileLogo: "/company/profile/logo",
  companyJobApplications: "/company/jobs/[jobId]/applications",
  seekerProfileAvatar: "/seeker/profile/avatar",
  seekerResumeExport: "/seeker/resume/export",
  seekerResumeDownload: "/seeker/resume/download"
} as const;
