FROM oven/bun:latest

WORKDIR /app
COPY package.json bun.lock* ./
COPY services/file-service/package.json services/file-service/package.json
COPY packages packages
RUN bun install

COPY . .
WORKDIR /app/services/file-service
CMD ["bun", "run", "dev"]
