FROM oven/bun:latest

WORKDIR /app
COPY package.json bun.lock* ./
COPY apps/backoffice/package.json apps/backoffice/package.json
COPY packages packages
RUN bun install

COPY . .
WORKDIR /app/apps/backoffice
CMD ["bun", "run", "dev"]
