export const colors = {
  primary: "#2563EB",
  primaryHover: "#1D4ED8",
  primarySoft: "#DBEAFE",
  primaryForeground: "#FFFFFF",
  secondary: "#0F172A",
  secondarySoft: "#E2E8F0",
  secondaryForeground: "#FFFFFF",
  accent: "#14B8A6",
  accentHover: "#0F766E",
  accentSoft: "#CCFBF1",
  background: "#FFFFFF",
  foreground: "#0F172A",
  muted: "#F8FAFC",
  mutedForeground: "#64748B",
  card: "#FFFFFF",
  cardForeground: "#0F172A",
  border: "#E2E8F0",
  input: "#CBD5E1",
  success: "#16A34A",
  successSoft: "#DCFCE7",
  warning: "#F59E0B",
  warningSoft: "#FEF3C7",
  danger: "#DC2626",
  dangerSoft: "#FEE2E2",
  info: "#0284C7",
  infoSoft: "#E0F2FE"
} as const;
