FROM oven/bun:latest

WORKDIR /app
COPY package.json bun.lock* ./
COPY apps/landingpage/package.json apps/landingpage/package.json
COPY packages packages
RUN bun install

COPY . .
WORKDIR /app/apps/landingpage
CMD ["bun", "run", "dev"]
