export enum ApplicationStatus {
  APPLIED = "APPLIED",
  REVIEWING = "REVIEWING",
  SHORTLISTED = "SHORTLISTED",
  APPOINTMENT_SCHEDULED = "APPOINTMENT_SCHEDULED",
  INTERVIEWED = "INTERVIEWED",
  OFFERED = "OFFERED",
  HIRED = "HIRED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED"
}
