events {}

http {
  upstream foundjob_landingpage {
    server foundjob-landingpage:3000;
  }

  upstream foundjob_backoffice {
    server foundjob-backoffice:3001;
  }

  server {
    listen 80;
    server_name localhost;

    location ^~ /public/ {
      alias /data/files/public/;
      try_files $uri =404;
      access_log off;
      expires 30d;
      add_header Cache-Control "public, max-age=2592000, immutable";
    }

    location ^~ /backoffice/ {
      proxy_pass http://foundjob_backoffice;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /backoffice {
      return 308 /backoffice/;
    }

    location ^~ /api/ {
      proxy_pass http://foundjob_landingpage;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      proxy_pass http://foundjob_landingpage;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
