FROM oven/bun:latest

WORKDIR /app
COPY package.json bun.lock* ./
COPY services/auth-service/package.json services/auth-service/package.json
COPY packages packages
RUN bun install

COPY . .
WORKDIR /app/services/auth-service
CMD ["bun", "run", "dev"]
